#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$(
	cd "$(dirname "$0")" || exit
	pwd -P
)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom
picom &

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
nitrogen --restore
dunst &

index=0
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width; do
	barname="mainbar0"
	monitor="$(polybar -m | tac | awk -v i="$((index + 1))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
	monitor=$monitor polybar -c "$SCRIPTPATH"/config.ini $barname &
	index=$((index + 1))
done
