[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1
themes = []

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "dracula"
directory = "/home/gabriel/.config/leftwm/themes/dracula"
version = "0.0.0"
leftwm_versions = "*"
current = true
